---
# tasks file for nginx
#
- name: Instalando Nginx
  apt:
    name: nginx
    state: present

- name: Copiando Vhost do Nginx
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/default.conf

- name: Removendo vhost default do nginx
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Criando link simbolico vhost
  file:
    src: /etc/nginx/sites-available/default.conf
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx  
