---
# tasks file for php
#
- name: Instalando PHP e suas extensoes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php-fpm
    - php-mysql
    - php-gd 
    - php-intl 
    - php-mbstring 
    - php-soap 
    - php-xml 
    - php-xmlrpc 
    - php-zip 

- name: Mudando propriedade cgi.fix_pathinfo=0 no php.ini
  lineinfile: dest=/etc/php/7.2/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify: restart php-fpm
  notify: restart nginx  
